verbosity: 10
server:
  host: 0.0.0.0
  port: 8080
  gracefulShutdownTimeout: 30
  accessLog:
    enabled: true

channels:
  hangoutsChat:
    myHangoutsChatChannel:
      # https://developers.google.com/hangouts/chat/how-tos/webhooks
      url: https://chat.googleapis.com/v1/spaces/CHAMGE_ME_SPACE_ID/messages?key=CHANGE_ME_KEY&token=CHANGE_ME_TOKEN

      # If you wish to post messages to single hangouts chat thread, uncommend bellow line and enter its ID
      # thread: CHANGE_ME_THREAD_ID

templates:
  hangoutsChat:
    myTemplateName:
      type: gotemplate-yaml # see: pkg/hangouts_chat/message_templates.go for examples of other formats
      template: |-
        text:
          Hi, <users/all>!!!

          {{ .some.text | toYaml }}
