verbosity: 10
server:
  host: 0.0.0.0
  port: 8080
  gracefulShutdownTimeout: 30
  accessLog:
    enabled: true

channels:
  hangoutsChat:
    myMonitoringChannel:
      url: "https://changeme.example.com/v1/webhook"
