apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-forwarder
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: miquidocompany/alertmanager-webhook-forwarder
          imagePullPolicy: IfNotPresent
          args:
            - serve
            - --config=/etc/config/config.yaml
          ports:
            - name: http-app
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 300m
              memory: 64Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/src/app/alertmanager-webhook-forwarder
                  - sleep
                  - "5"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-app
              httpHeaders:
                - name: x-k8s-probe
                  value: readiness
            initialDelaySeconds: 1
            periodSeconds: 3
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-app
              httpHeaders:
                - name: x-k8s-probe
                  value: liveness
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
            - name: config-yaml
              mountPath: /etc/config
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: config-yaml
          configMap:
            name: alertmanager-webhook-forwarder-config
