apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-forwarder
  labels:
    app.kubernetes.io/name: alertmanager-webhook-forwarder
    app.kubernetes.io/component: server
    app.kubernetes.io/tier: backend
    app.kubernetes.io/environment: dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: alertmanager-webhook-forwarder
    app.kubernetes.io/component: server
    app.kubernetes.io/tier: backend
    app.kubernetes.io/environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-forwarder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-webhook-forwarder
      app.kubernetes.io/component: server
      app.kubernetes.io/tier: backend
      app.kubernetes.io/environment: dev
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-webhook-forwarder
        app.kubernetes.io/component: server
        app.kubernetes.io/tier: backend
        app.kubernetes.io/environment: dev
    spec:
      containers:
        - name: api
          image: docker.io/miquidocompany/alertmanager-webhook-forwarder:0.2.1
          args:
            - serve
            - --host=0.0.0.0
            - --port=8080
            - --config=/etc/config/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: config-yaml
              mountPath: /etc/config
      volumes:
        - name: config-yaml
          configMap:
            name: alertmanager-webhook-forwarder-config
