kind: Kustomization
commonLabels:
  app.kubernetes.io/name: alertmanager-webhook-forwarder
  app.kubernetes.io/component: server
  app.kubernetes.io/tier: backend
  app.kubernetes.io/environment: dev
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: miquidocompany/alertmanager-webhook-forwarder
    newTag: latest
configMapGenerator:
  - name: alertmanager-webhook-forwarder-config
    files:
      - config.yaml
