POST http://localhost:8080/v1/webhook/hangouts-chat?channel=test&template=fabfuelECSDeploy&successStatusCode=200
Content-Type: application/json

{
  "attachments": [
    {
      "color": null,
      "fields": [
        {
          "short": true,
          "title": "Cluster",
          "value": "youmap-development-main"
        },
        {
          "short": true,
          "title": "Service",
          "value": "youmap-development-api-node"
        },
        {
          "short": true,
          "title": "Tag",
          "value": "0.0.1-dev-119"
        }
      ],
      "pretext": "Deployment has started"
    }
  ],
  "username": "ECS Deploy"
}

###

POST http://localhost:8080/v1/webhook/hangouts-chat?channel=test&template=fabfuelECSDeploy&successStatusCode=200
Content-Type: application/json

{
  "attachments": [
    {
      "color": "good",
      "fields": [
        {
          "short": true,
          "title": "Cluster",
          "value": "youmap-development-main"
        },
        {
          "short": true,
          "title": "Service",
          "value": "youmap-development-api-node"
        },
        {
          "short": true,
          "title": "Revision",
          "value": 141
        },
        {
          "short": true,
          "title": "Duration",
          "value": "0:01:57.735686"
        }
      ],
      "pretext": "Deployment finished successfully"
    }
  ],
  "username": "ECS Deploy"
}

###
